version: '3.1'
services:
  stats-server:
    build: ./statistic/stat_service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats
    restart: always
    ports:
      - "9091:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stats
    volumes:
      - ./db/stat_init.sql:/docker-entrypoint-initdb.d/init.sql

  ewm-service:
    build: ./emw
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm
    restart: always
    ports:
      - "8081:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ewm
    volumes:
      - ./db/ewm_init.sql:/docker-entrypoint-initdb.d/init.sql
