DROP TABLE IF EXISTS compilation_event;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS participations;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS status;
DROP TYPE IF EXISTS state;

CREATE TYPE state AS ENUM ('PENDING', 'PUBLISHED', 'CANCELED');

CREATE TYPE status AS ENUM ('PENDING', 'PUBLISHED', 'CANCELED');

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    annotation         VARCHAR                                 NOT NULL,
    description        VARCHAR                                 NOT NULL,
    category           BIGINT
        CONSTRAINT event_category_id_fk REFERENCES categories (id),
    created            TIMESTAMP WITHOUT TIME ZONE,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator          BIGINT
        CONSTRAINT event_initiator_id_fk REFERENCES users (id),
    latitude           FLOAT                                   NOT NULL,
    longitude          FLOAT                                   NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INT                                     NOT NULL DEFAULT 0,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                                 NOT NULL DEFAULT TRUE,
    state              STATE                                   NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_event PRIMARY KEY (id)
    --  views
    --  confirmedRequests
);

CREATE TABLE IF NOT EXISTS participations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester BIGINT
        CONSTRAINT participation_user_id_fk REFERENCES USERS (ID),
    event     BIGINT
        CONSTRAINT participation_event_id_fk REFERENCES EVENTS (ID),
    created   TIMESTAMP WITHOUT TIME ZONE,
    status    status                                  NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_participation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    pinned BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id BIGINT
        CONSTRAINT compilation_id_fk REFERENCES COMPILATIONS (ID),
    event_id       BIGINT
        CONSTRAINT event_id_fk REFERENCES EVENTS (ID),
    CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT unique_compilation_event UNIQUE (compilation_id, event_id)
);

